article/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from article.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    toggle_activity
from article.apps import ArticleConfig
app_name = ArticleConfig.name
urlpatterns = [
    path('articles/create/', never_cache(ArticleCreateView.as_view()), name="create_article"),
    path('articles/update/<int:pk>/', never_cache(ArticleUpdateView.as_view()), name="update_article"),
    path('articles/', ArticleListView.as_view(), name="articles"),
    path('articles/<slug:slug>/', ArticleDetailView.as_view(), name="article_detail"),
    path('articles/delete/<int:pk>/', ArticleDeleteView.as_view(), name="delete_article"),
    path('articles/publish/<int:pk>/', toggle_activity, name="toggle_activity"),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('', include(('article.urls', 'article'), namespace='article')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserPasswordResetView, ProfileView

app_name = UsersConfig.name
urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='token'),
    path('reset-password/', UserPasswordResetView.as_view(), name='reset_password'),
    path('profile/', ProfileView.as_view(), name='profile'),

]

article/models.py
from django.db import models
NULLABLE = {'null': True, 'blank': True}


class Article(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='articles/', verbose_name='Изображение', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    view_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

article/forms.py
from django import forms
from django.forms import BooleanField

from article.models import Article


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ArticleManagerForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Article
        exclude = ('slug', 'created_at', 'view_count')

article/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse

from article.forms import ArticleManagerForm
from article.models import Article
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    form_class = ArticleManagerForm
    success_url = reverse_lazy('article:articles')

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()

        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user.has_perm("article.change_article"):
            return ArticleManagerForm
        raise PermissionDenied


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    form_class = ArticleManagerForm
    success_url = reverse_lazy('article:articles')

    def get_success_url(self):
        return reverse('article:article_detail', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()

        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user.has_perm("article.change_article"):
            return ArticleManagerForm
        raise PermissionDenied


class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('article:articles')


class ArticleListView(ListView):
    model = Article
    template_name = 'article/articles_list.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)

        return queryset


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article/article_detail.html'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


def toggle_activity(request, pk):
    article_item = get_object_or_404(Article, pk=pk)
    if article_item.is_published:
        article_item.is_published = False
    else:
        article_item.is_published = True

    article_item.save()
    return redirect(reverse('article:articles'))

article/templates/article/article_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Хотите удалить статью {{object.title}}</h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-danger">Подтвердить</button>
                        <a href="{% url 'article:articles' %}" type="button" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

article/templates/article/article_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h3 class="my-0 font-weight-normal">{{ article.title }}</h3>
                </div>
                <div class="card-body">
                    <img src= "{{ article.preview|mymedia }}" height="200" class="img">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ article.content }}</li>
                    </ul>
                    {% if perms.article.add_article and perms.article.change_article and perms.delete_article %}
                    <a href="{% url 'article:update_article' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
                    <a href="{% url 'article:delete_article' object.pk %}" type="button" class="btn btn-lg btn-block btn-danger">Удалить</a>
                    {% endif %}
                </div>
                <div class="card-footer">
                    Просмотры {{ object.view_count }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

article/templates/article/article_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Загрузите статью</h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {{form.as_p}}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Создать</button>
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

article/templates/article/articles_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row text-center">
    {% for object in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h3 class="my-0 font-weight-normal">{{ object.title }}</h3>
            </div>
            <div class="card-body">
<!--                <img src="/media/{{ object.preview }}" height="111" class="img-thumbnail">-->
                <img src="{{ object.preview|mymedia }}" height="111" class="img-thumbnail">
                <span class="textarea">{{ object.content|slice:100 }}</span>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                </ul>
                <a href="{% url 'article:article_detail' object.slug %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Читать</a>
                {% if perms.article.add_article and perms.article.change_article and perms.delete_article %}
                {% if object.is_published %}
                    <a href="{% url 'article:toggle_activity' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Снять с публикации</a>
                {% else %}
                    <a href="{% url 'article:toggle_activity' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Опубликовать</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}